// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: blockchain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockChainClient is the client API for BlockChain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockChainClient interface {
	GetTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error)
	GetBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Response, error)
	GetBlockChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*Chain, error)
	GetUtxoSet(ctx context.Context, in *UtxoRequest, opts ...grpc.CallOption) (*Utxo, error)
}

type blockChainClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockChainClient(cc grpc.ClientConnInterface) BlockChainClient {
	return &blockChainClient{cc}
}

func (c *blockChainClient) GetTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.BlockChain/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.BlockChain/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetBlockChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*Chain, error) {
	out := new(Chain)
	err := c.cc.Invoke(ctx, "/proto.BlockChain/GetBlockChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetUtxoSet(ctx context.Context, in *UtxoRequest, opts ...grpc.CallOption) (*Utxo, error) {
	out := new(Utxo)
	err := c.cc.Invoke(ctx, "/proto.BlockChain/GetUtxoSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockChainServer is the server API for BlockChain service.
// All implementations must embed UnimplementedBlockChainServer
// for forward compatibility
type BlockChainServer interface {
	GetTransaction(context.Context, *Transaction) (*Response, error)
	GetBlock(context.Context, *Block) (*Response, error)
	GetBlockChain(context.Context, *ChainRequest) (*Chain, error)
	GetUtxoSet(context.Context, *UtxoRequest) (*Utxo, error)
	mustEmbedUnimplementedBlockChainServer()
}

// UnimplementedBlockChainServer must be embedded to have forward compatible implementations.
type UnimplementedBlockChainServer struct {
}

func (UnimplementedBlockChainServer) GetTransaction(context.Context, *Transaction) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedBlockChainServer) GetBlock(context.Context, *Block) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedBlockChainServer) GetBlockChain(context.Context, *ChainRequest) (*Chain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockChain not implemented")
}
func (UnimplementedBlockChainServer) GetUtxoSet(context.Context, *UtxoRequest) (*Utxo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUtxoSet not implemented")
}
func (UnimplementedBlockChainServer) mustEmbedUnimplementedBlockChainServer() {}

// UnsafeBlockChainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockChainServer will
// result in compilation errors.
type UnsafeBlockChainServer interface {
	mustEmbedUnimplementedBlockChainServer()
}

func RegisterBlockChainServer(s grpc.ServiceRegistrar, srv BlockChainServer) {
	s.RegisterService(&BlockChain_ServiceDesc, srv)
}

func _BlockChain_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlockChain/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlockChain/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetBlock(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetBlockChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetBlockChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlockChain/GetBlockChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetBlockChain(ctx, req.(*ChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetUtxoSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UtxoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetUtxoSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlockChain/GetUtxoSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetUtxoSet(ctx, req.(*UtxoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockChain_ServiceDesc is the grpc.ServiceDesc for BlockChain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockChain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BlockChain",
	HandlerType: (*BlockChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransaction",
			Handler:    _BlockChain_GetTransaction_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _BlockChain_GetBlock_Handler,
		},
		{
			MethodName: "GetBlockChain",
			Handler:    _BlockChain_GetBlockChain_Handler,
		},
		{
			MethodName: "GetUtxoSet",
			Handler:    _BlockChain_GetUtxoSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain.proto",
}
